### ISSUE TITLE
Typo in tags in `.github/workflows/release.yaml` ?

### ISSUE THREAD

**Issue by Lex-DRL** [ArjanCodes/moneysnake#7]
There seems to be a typo in `release.yaml` shown in your [YouTube video](https://www.youtube.com/watch?v=NMQwzI9hprg).
I might be wrong, since I'm not yet familiar with GitHub automation, but I'm familiar with regex. `.` (dot) character normally means not the dot itself, but represents any character.

So the current regex: `"[0-9]+.[0-9]+.[0-9]+"` matches `123.456.789`, as well as `123q456w789`, or even `123^456?789`.
If this wasn't intended and this specific odd usage of dot isn't a quirk of GitHub, dots need to be escaped: `\.` or `\\.`, depending on how GitHub interprets regex strings.

**Comment by TimEvci** [comment]
@Lex-DRL GitHub Actions uses a [filtering syntax](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet) that resembles regex but is actually based on glob patterns. You're correct that in regex, the dot must be escaped to match a literal dot. However, in glob patterns, the dot is treated as a literal character by default and does not require escaping.

Edit: That being said, I see that we are not using the filtering syntax correctly. Thank you for noticing, will fix it in the new release.

**Comment by TimEvci** [comment]
@Lex-DRL upon revisiting [the docs for Github Actions](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore), the syntax we use is actually correct. 

> The branches, branches-ignore, tags, and tags-ignore keywords accept glob patterns that use characters like *, **, +, ?, ! and others to match more than one branch or tag name. If a name contains any of these characters and you want a literal match, you need to escape each of these special characters with \. 

The dot is being used a literal character, while other special characters are used for glob pattern matching.
